### ISSUE TITLE
What's the scalability of the bot?

### ISSUE THREAD

**Issue by preethamcoder** [HackBinghamton/DiscordBotWorkshop#5]
Can it support concurrent usage in multiple servers?

**Comment by preethamcoder** [comment]
I actually built a bot too, but I was not able to support it on multiple servers. 

Here's the bot: https://github.com/preethamcoder/DolGod101-Bot

**Comment by CodingKoopa** [comment]
Thank you for your inquiry. There's not much of a bot here, all it does is respond to a message with a constant string. 

The title and body of this issue are a little different. To have the bot be able to used in more than one server at once should be trivial, especially when it comes to handling messages (as opposed to, like, sitting in a voice channel). If handling one command prevents the bot from taking another, then your code is blocking when it shouldn't be, though I don't see any obvious indicators in your code of this.

As far as "scalability" goes, that is getting into sharding which is a separate thing that I can't speak on.

I hope this answers the question about this repo.

**Comment by preethamcoder** [comment]
Thank you for your response, @CodingKoopa! I really appreciate it.
The bot was able to respond to messages without too much of a problem. I was asking if there was a way to make the bot participate in multiple voice channels at once (in different servers)?
